import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "samur-portal-paciente",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body style={{ fontFamily: 'urbanist', backgroundColor:"var(--branco)" }}>{children}</body>
    </html>
  );
}
